import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const STRINGS = {
  en: {
    // ── nav ──────────────────────────────────────────────────────────────────
    'nav.home':'Home','nav.bestxi':'Best XI','nav.players':'Players','nav.fixtures':'Fixtures',
    'nav.stats':'Stats','nav.compare':'Compare','nav.methodology':'Methodology',

    // ── home ─────────────────────────────────────────────────────────────────
    'home.hero_eyebrow':'Updated 2 hours ago · Matchweek 38',
    'home.hero_title1':'THE BEST XI.',
    'home.hero_title2':'RIGHT NOW.',
    'home.hero_body':'Data-driven ratings for every Moroccan professional footballer worldwide — from La Liga to the Botola to the Saudi Pro League. Updated daily.',
    'home.btn_build':'Build the Best XI',
    'home.btn_browse':'Browse Players',
    'home.counter_players':'Players tracked',
    'home.counter_leagues':'Leagues monitored',
    'home.counter_matches':'Matches indexed',
    'home.form_guide':'Form Guide',
    'home.current_xi_title':'Current Best XI',
    'home.current_xi_subtitle':'4-3-3 · Last 30 days · All competitions',
    'home.customise':'Customise',
    'home.starting_xi_label':'Starting XI · Top rated',
    'home.more_click':'+ 4 more · Click "Customise" to change formation, window & league filter',
    'home.rising_eyebrow':'↑ Form Guide',
    'home.rising_title':'Rising — last 14 days',
    'home.rising_subtitle':'Players with the biggest rating jumps',
    'home.nt_eyebrow':'Atlas Lions',
    'home.nt_title':'Upcoming international fixtures',
    'home.no_fixtures':'No upcoming fixtures found',
    'home.method_eyebrow':'Methodology',
    'home.method_title':'How we rate',
    'home.method_body':'Every rating carries a data-quality badge. We use Sofascore for breadth and a custom xT/VAEP model for Big 5 + SPL where event data is available.',
    'home.method_btn':'Read the methodology',
    'home.atlas_on_pitch':'Atlas Lions on pitch',

    // ── bestxi ───────────────────────────────────────────────────────────────
    'bestxi.title':'Build the Best XI',
    'bestxi.flagship':'The Flagship',
    'bestxi.page_title':'BUILD THE BEST XI',
    'bestxi.description':'Pick a formation, a window, and which leagues count. The optimiser fills each position with the highest-rated eligible player. Click any slot to swap in a substitute — the pitch updates live, and Auto-fill restores the optimal XI.',
    'bestxi.formation':'Formation',
    'bestxi.window':'Time Window',
    'bestxi.window_2mw':'2 MW',
    'bestxi.window_1mo':'1 MONTH',
    'bestxi.window_2mo':'2 MONTHS',
    'bestxi.window_3mo':'3 MONTHS',
    'bestxi.league_filter':'League Filter',
    'bestxi.bucket_all':'All',
    'bestxi.bucket_clear':'Clear',
    'bestxi.rating_method':'Rating Method',
    'bestxi.method_commercial_title':'Commercial',
    'bestxi.method_commercial_sub':'Sofascore — 200+ leagues',
    'bestxi.method_custom_title':'Custom xT/VAEP',
    'bestxi.method_custom_sub':'Event data — Big 5 + SPL',
    'bestxi.min_minutes':'Minimum Minutes',
    'bestxi.min_minutes_note':'Players with fewer minutes in the window are excluded.',
    'bestxi.generate':'Generate Best XI',
    'bestxi.optimising':'Optimising…',
    'bestxi.commercial':'Commercial',
    'bestxi.custom':'Custom xT/VAEP',
    'bestxi.caveat':'Rankings reflect recent form only.',
    'bestxi.heuristic_warning':'Custom ratings unavailable for Botola/MENA — heuristic scores shown.',
    'bestxi.optimised':'Optimised',
    'bestxi.manually_edited':'Manually edited',
    'bestxi.eligible':'ELIGIBLE',
    'bestxi.reset_optimal':'Reset to optimal',
    'bestxi.autofill':'Auto-fill',
    'bestxi.export_png':'Export PNG',
    'bestxi.share_xi':'Share XI',
    'bestxi.optimiser_details':'Optimiser details',
    'bestxi.detail_formation':'Formation',
    'bestxi.detail_window':'Window',
    'bestxi.detail_method':'Method',
    'bestxi.detail_min_minutes':'Min minutes',
    'bestxi.detail_buckets':'Buckets',
    'bestxi.detail_candidates':'Candidates',
    'bestxi.detail_event_rated':'Event-rated',
    'bestxi.detail_mean_rating':'Mean rating',
    'bestxi.detail_days':'days',
    'bestxi.swap_note':'click to swap in cover',
    'bestxi.status_doubtful':'Doubtful',
    'bestxi.status_injured':'Injured',
    'bestxi.status_suspended':'Suspended',
    'bestxi.status_unknown':'Unknown',
    'bestxi.caveat_label':'Caveat',
    'bestxi.caveat_suffix':'This is not a selection recommendation — tactical fit, chemistry, and injuries are not modelled.',
    'bestxi.click_swap':'click the slot to swap in cover',
    'bestxi.player_status_alert':'({slot}) is {status}',
    'bestxi.detail_pool':'Pool size',
    'bestxi.detail_data_quality':'Data quality',

    // ── players ───────────────────────────────────────────────────────────────
    'players.title':'PLAYERS',
    'players.next_gen':'★ The Next Generation',
    'players.active_profiles':'{n} active profiles',
    'players.lens_all':'All Players',
    'players.lens_rising':'★ Rising Stars',
    'players.rising_desc':'Players under {age} with Morocco-eligible nationality — including dual nationals potentially switchable under FIFA Article 9.',
    'players.article9_title':'FIFA Article 9 · Eligibility data is community-sourced.',
    'players.article9_body':'Players who hold Moroccan nationality and have not played a competitive senior match for another association can switch. Always verify with FRMF.',
    'players.filters':'Filters',
    'players.sort_rating':'Rating ↓',
    'players.sort_mv':'Market value ↓',
    'players.sort_age':'Age ↑',
    'players.sort_minutes':'Minutes ↓',
    'players.sort_name':'Name A→Z',
    'players.cancel_compare':'Cancel compare',
    'players.compare':'Compare',
    'players.club_country':'Club country',
    'players.all':'All',
    'players.eligible':'Eligible',
    'players.switchable':'Switchable',
    'players.capped':'Capped',
    'players.filter_position':'Position',
    'players.filter_bucket':'League bucket',
    'players.filter_age_max':'Age max',
    'players.filter_quality':'Data quality',
    'players.bucket_big5':'Big 5',
    'players.bucket_other_eu':'Other EU',
    'players.bucket_botola':'Botola',
    'players.bucket_mena':'MENA',
    'players.reset_filters':'Reset filters',
    'players.showing':'Showing {count} of {total} players',
    'players.grid':'Grid',
    'players.table':'Table',
    'players.selected_n':'{n} selected',
    'players.selected_min2':'pick at least 2',
    'players.compare_n':'Compare {n}',
    'players.col_player':'Player',
    'players.col_pos':'Pos',
    'players.col_club':'Club',
    'players.col_league':'League',
    'players.col_rating':'Rating',
    'players.col_mv':'MV',
    'players.col_min':'Min',
    'players.col_data':'Data',
    'players.col_elig':'Elig.',
    'players.age_controlled':'Age is controlled by the U-19/21/23 filter above in Rising Stars view.',
    'players.loading':'Loading players…',
    'players.no_match':'No players match',
    'players.no_match_desc':'Try widening filters or clearing the search.',
    'players.reset_all':'Reset all',

    // ── player (detail) ───────────────────────────────────────────────────────
    'player.breadcrumb_home':'Home',
    'player.breadcrumb_players':'Players',
    'player.rating_30d':'30-day avg',
    'player.compare_btn':'Compare →',
    'player.tab_performance':'Performance',
    'player.tab_history':'Match history',
    'player.form_averages':'Form averages by window',
    'player.no_rating_data':'No rating data in database yet — run a sync to populate match stats.',
    'player.rating_history':'Rating history · last {n} days',
    'player.matches':'matches',
    'player.filter_all':'All',
    'player.filter_national':'National',
    'player.filter_club':'Club',
    'player.heatmap_title':'Form heatmap · last 365 days',
    'player.no_matches_window':'No matches in this window',
    'player.no_matches_window_desc':'Try a wider window or run a sync.',
    'player.all_matches':'All matches',
    'player.no_match_data':'No match data',
    'player.no_match_data_desc':'Run a sync to pull match stats from API-Football.',
    'player.col_date':'Date',
    'player.col_match':'Match',
    'player.col_competition':'Competition',
    'player.col_min':'Min',
    'player.col_goals':'G',
    'player.col_assists':'A',
    'player.col_rating':'Rating',
    'player.col_quality':'Quality',
    'player.loading':'Loading player…',
    'player.not_found':'Player not found',
    'player.not_found_desc':'Check the URL or browse the directory.',
    'player.back':'Back to players',
    'player.stat_age':'Age',
    'player.stat_height':'Height',
    'player.stat_foot':'Foot',
    'player.stat_mv':'Market value',
    'player.stat_season_min':'Season min.',
    'player.rating':'Rating','player.position':'Position','player.club':'Club',
    'player.market_value':'Market Value','player.age':'Age','player.minutes':'Minutes',
    'player.archetype':'Archetype','player.eligibility':'Eligibility','player.data_quality':'Data Quality',

    // ── compare ───────────────────────────────────────────────────────────────
    'compare.eyebrow':'Up to 4 players · cross-league',
    'compare.title':'COMPARE',
    'compare.add_player':'Add player',
    'compare.radar_title':'Profile radar',
    'compare.sidebyside_title':'Side-by-side',
    'compare.metric':'Metric',
    'compare.footnote':'Cross-league comparisons are positional z-scores within bucket. Heuristic-rated leagues are not directly commensurable with event-data leagues — see Methodology.',
    'compare.need_two':'Add at least 2 players to compare them side-by-side.',
    'compare.picker_subtitle':'Pick anyone from the database',
    'compare.metric_rating':'Rating',
    'compare.metric_attack':'Attack',
    'compare.metric_defence':'Defence',
    'compare.metric_passing':'Passing',
    'compare.metric_dribble':'Dribble',
    'compare.metric_minutes':'Minutes',
    'compare.metric_value':'Value',
    'compare.metric_xt':'xT/90',

    // ── fixtures ──────────────────────────────────────────────────────────────
    'fixtures.eyebrow':'Match Centre',
    'fixtures.title':'FIXTURES',
    'fixtures.live_now':'LIVE NOW',
    'fixtures.bucket_all':'All',
    'fixtures.bucket_big5':'Big 5',
    'fixtures.bucket_other_eu':'Other EU',
    'fixtures.bucket_botola':'Botola',
    'fixtures.bucket_mena':'MENA',
    'fixtures.bucket_international':'International',
    'fixtures.sort_date':'By date',
    'fixtures.sort_competition':'By competition',
    'fixtures.sort_players':'By Atlas Lions count',
    'fixtures.nt_only':'NT only',
    'fixtures.list':'List',
    'fixtures.calendar':'Calendar',
    'fixtures.type_international':'International',
    'fixtures.type_continental':'Continental',
    'fixtures.type_cup':'Cup',
    'fixtures.type_league':'League',
    'fixtures.today':'TODAY',
    'fixtures.matches':'MATCHES',
    'fixtures.prev':'‹ Prev',
    'fixtures.next':'Next ›',
    'fixtures.close':'Close ×',
    'fixtures.no_fixtures':'No fixtures',
    'fixtures.no_fixtures_desc':'No matches match the current filters.',
    'fixtures.by_lions':'By Atlas Lions involved',
    'fixtures.atlas_on_pitch':'Atlas Lions on pitch',

    // ── stats ─────────────────────────────────────────────────────────────────
    'stats.eyebrow':'National Team · {year} · {n} internationals',
    'stats.title':'MOROCCO — ATLAS LIONS',
    'stats.form_last10':'Form · last 10',
    'stats.goals_scored':'Goals scored',
    'stats.goals_conceded':'Goals conceded',
    'stats.clean_sheets':'Clean sheets',
    'stats.win_rate':'Win rate',
    'stats.vs_prev':'vs {year}',
    'stats.goals_chart_title':'Goals per match',
    'stats.goals_chart_sub':'Last 20 internationals',
    'stats.xg_chart_title':'xG vs goals scored',
    'stats.xg_chart_sub':'Finishing vs expected · last 20',
    'stats.top_contrib':'Top contributors',
    'stats.top_contrib_sub':'Morocco-only ratings · last 365 days',
    'stats.col_rank':'#',
    'stats.col_player':'Player',
    'stats.col_caps':'Caps',
    'stats.col_goals':'G',
    'stats.col_assists':'A',
    'stats.col_avg':'Avg',
    'stats.recent_results':'Recent results',
    'stats.goals_label':'Goals',
    'stats.xg_label':'xG',

    // ── methodology ───────────────────────────────────────────────────────────
    'methodology.eyebrow':'Transparency',
    'methodology.title':'METHODOLOGY',
    'methodology.intro':'How Atlas Lions Analytics rates every Moroccan professional footballer and what the numbers actually mean.',
    'methodology.rating_scale_title':'Rating scale',
    'methodology.rating_scale_body':'We use the Sofascore 3–10 scale as our baseline. Sofascore covers 200+ leagues and provides the broadest cross-competition coverage available for professional football. Their rating combines pass success, duels, key passes, goals, assists, and conceded goals (for GKs).',
    'methodology.tier_exceptional':'Exceptional',
    'methodology.tier_good':'Good',
    'methodology.tier_belowpar':'Below par',
    'methodology.quality_title':'Data quality tiers',
    'methodology.quality_body':'Not all ratings are equal. Every player\'s form rating carries a data-quality badge to indicate how reliable the underlying data is.',
    'methodology.event_title':'Event data — xT/VAEP model',
    'methodology.event_body':'Available for Big 5 leagues (Premier League, La Liga, Bundesliga, Serie A, Ligue 1) and the Saudi Pro League. Uses StatsBomb Open Data or licensed feeds to compute expected threat (xT) and value of actions using estimated probabilities (VAEP). Normalised to the 4–9 scale for comparability.',
    'methodology.commercial_title':'Commercial rating — Sofascore',
    'methodology.commercial_body':'The raw Sofascore match rating, used as-is for leagues outside the Big 5 + SPL. Covers Botola Pro, Ligue 1 Professionnelle, Saudi Division 1, and most other leagues tracked. Subject to Sofascore\'s own editorial model.',
    'methodology.heuristic_title':'Heuristic — derived estimate',
    'methodology.heuristic_body':'For leagues with incomplete Sofascore coverage, we derive a form estimate from available partial data: minutes played, goals, assists, and clean sheets. Treat these as rough guides only — not directly comparable to event or commercial ratings.',
    'methodology.bestxi_title':'The Best XI optimiser',
    'methodology.bestxi_body':'The Best XI uses a Hungarian algorithm (Kuhn-Munkres) — an O(n³) assignment optimiser — to find the globally optimal assignment of players to formation slots. Each slot has a list of eligible positions (e.g., the RB slot accepts RB, WB, RM), and each player has a primary position plus eligible slot list.',
    'methodology.bestxi_callout':'Algorithm: We build a cost matrix where cost(player, slot) = 10 − player.formRating if player.pos ∈ slot.eligiblePositions, else ∞. The Hungarian algorithm minimises total cost, which is equivalent to maximising total rating. Ties are broken by data quality (event > rating > heuristic).',
    'methodology.bestxi_body2':'If fewer than 11 players meet the minimum-minutes threshold, the system relaxes the threshold to 0 and shows a "Relaxed" warning. The optimiser runs client-side on mock data in this demo; in production it queries the backend API which caches results in Redis with a 1-hour TTL.',
    'methodology.league_weighting_title':'League weighting',
    'methodology.league_weighting_body':'Leagues are grouped into buckets. The bucket affects which players are eligible for Best XI calculations and how ratings are weighted in cross-bucket comparisons.',
    'methodology.col_bucket':'Bucket',
    'methodology.col_leagues':'Leagues',
    'methodology.col_quality':'Data quality',
    'methodology.col_weight':'Weight',
    'methodology.eligibility_title':'Eligibility classification',
    'methodology.eligibility_body':'Every player is classified into one of four eligibility categories:',
    'methodology.elig_capped_label':'Capped',
    'methodology.elig_capped_desc':'Has played a competitive senior international for Morocco (or is already locked in for Morocco).',
    'methodology.elig_eligible_label':'Eligible',
    'methodology.elig_eligible_desc':'Holds Moroccan nationality and has not been capped by any senior national team. Can play for Morocco immediately.',
    'methodology.elig_switchable_label':'Switchable',
    'methodology.elig_switchable_desc':'Currently registered with another national team but has not yet played a competitive match. May switch to Morocco under FIFA Article 9 if they hold Moroccan citizenship.',
    'methodology.elig_prospect_label':'Prospect',
    'methodology.elig_prospect_desc':'Has Moroccan heritage but dual nationality is unconfirmed or complex. Community-sourced; verify independently.',
    'methodology.caveats_title':'Caveats & limitations',
    'methodology.caveats_callout':'This is not a selection recommendation. Ratings reflect recent statistical form only. They do not account for tactical fit, team chemistry, psychological factors, or coach preferences. Rankings are provided for analytical entertainment and debate purposes only.',
    'methodology.caveats_body':'Additional limitations to be aware of:',
    'methodology.caveat1':'Players with fewer than 90 minutes in the selected window may have unstable ratings due to small sample size.',
    'methodology.caveat2':'Sofascore ratings can be affected by the match context — a player who scores an 88th-minute winner in a 1-0 game may receive a disproportionately high rating.',
    'methodology.caveat3':'Cross-league comparisons should be treated with caution. A 7.5 in the Botola is not the same as a 7.5 in the Premier League.',
    'methodology.caveat4':'Eligibility data is community-sourced and may be out of date. Always verify with the player\'s club or FRMF before drawing conclusions.',
    'methodology.caveat5':'This platform is not affiliated with FRMF, the Moroccan Football Federation.',
    'methodology.sources_title':'Data sources',
    'methodology.source_sofascore':'Match ratings for 200+ leagues',
    'methodology.source_apifootball':'Live scores, fixtures, lineups',
    'methodology.source_transfermarkt':'Market values, career history',
    'methodology.source_wikidata':'Nationality and biographical data',
    'methodology.source_statsbomb':'xT/VAEP event data (Big 5)',
    'methodology.source_fbref':'Advanced stats for Big 5 leagues',

    // ── notfound ──────────────────────────────────────────────────────────────
    'notfound.title':'PAGE NOT FOUND',
    'notfound.desc':'The page you\'re looking for doesn\'t exist. It may have been moved, or the URL might be wrong.',
    'notfound.go_home':'Go home',
    'notfound.browse':'Browse players',

    // ── footer ────────────────────────────────────────────────────────────────
    'footer.tagline':'Data-driven insights for the Atlas Lions — every Moroccan professional, every league, every weekend.',
    'footer.disclaimer':'Rankings reflect recent form only — not a selection recommendation. Not affiliated with FRMF.',
    'footer.navigate':'Navigate',
    'footer.sources':'Data sources',

    // ── common ────────────────────────────────────────────────────────────────
    'common.loading':'Loading…','common.search':'Search players, clubs…','common.filter':'Filter',
    'common.reset':'Reset','common.share':'Share','common.view_all':'View all',
  },

  // ════════════════════════════════════════════════════════════════════════════
  fr: {
    // ── nav ──────────────────────────────────────────────────────────────────
    'nav.home':'Accueil','nav.bestxi':'Onze idéal','nav.players':'Joueurs','nav.fixtures':'Matchs',
    'nav.stats':'Stats','nav.compare':'Comparer','nav.methodology':'Méthodologie',

    // ── home ─────────────────────────────────────────────────────────────────
    'home.hero_eyebrow':'Mis à jour il y a 2 h · Journée 38',
    'home.hero_title1':'LE MEILLEUR XI.',
    'home.hero_title2':'EN CE MOMENT.',
    'home.hero_body':'Des statistiques pour chaque footballeur professionnel marocain dans le monde — de La Liga à la Botola. Mis à jour chaque jour.',
    'home.btn_build':'Construire le Onze',
    'home.btn_browse':'Parcourir les joueurs',
    'home.counter_players':'Joueurs suivis',
    'home.counter_leagues':'Ligues surveillées',
    'home.counter_matches':'Matchs indexés',
    'home.form_guide':'Forme récente',
    'home.current_xi_title':'Onze actuel',
    'home.current_xi_subtitle':'4-3-3 · 30 derniers jours · Toutes compétitions',
    'home.customise':'Personnaliser',
    'home.starting_xi_label':'XI de départ · Mieux notés',
    'home.more_click':'+ 4 autres · Cliquez sur "Personnaliser" pour changer la formation',
    'home.rising_eyebrow':'↑ Forme',
    'home.rising_title':'En hausse — 14 derniers jours',
    'home.rising_subtitle':'Joueurs avec les plus fortes progressions',
    'home.nt_eyebrow':'Atlas Lions',
    'home.nt_title':'Prochains matchs internationaux',
    'home.no_fixtures':'Aucun match à venir',
    'home.method_eyebrow':'Méthodologie',
    'home.method_title':'Comment on évalue',
    'home.method_body':'Chaque note est accompagnée d\'un badge de qualité. Nous utilisons Sofascore pour la couverture large et un modèle xT/VAEP pour le Big 5 + SPL.',
    'home.method_btn':'Lire la méthodologie',
    'home.atlas_on_pitch':'Lions de l\'Atlas sur le terrain',

    // ── bestxi ───────────────────────────────────────────────────────────────
    'bestxi.title':'Composer le Onze idéal',
    'bestxi.flagship':'Le Phare',
    'bestxi.page_title':'CONSTRUIRE LE ONZE',
    'bestxi.description':'Choisissez une formation, une période et les ligues à inclure. L\'optimiseur sélectionne le joueur le mieux noté pour chaque poste. Cliquez sur un slot pour effectuer un remplacement — le terrain se met à jour en direct.',
    'bestxi.formation':'Schéma',
    'bestxi.window':'Période',
    'bestxi.window_2mw':'2 JO',
    'bestxi.window_1mo':'1 MOIS',
    'bestxi.window_2mo':'2 MOIS',
    'bestxi.window_3mo':'3 MOIS',
    'bestxi.league_filter':'Filtre des ligues',
    'bestxi.bucket_all':'Tout',
    'bestxi.bucket_clear':'Vider',
    'bestxi.rating_method':'Méthode',
    'bestxi.method_commercial_title':'Commerciale',
    'bestxi.method_commercial_sub':'Sofascore — 200+ ligues',
    'bestxi.method_custom_title':'xT/VAEP',
    'bestxi.method_custom_sub':'Données évén. — Big 5 + SPL',
    'bestxi.min_minutes':'Minutes minimum',
    'bestxi.min_minutes_note':'Les joueurs avec moins de minutes dans la fenêtre sont exclus.',
    'bestxi.generate':'Générer le Onze',
    'bestxi.optimising':'Optimisation…',
    'bestxi.commercial':'Commerciale',
    'bestxi.custom':'xT/VAEP',
    'bestxi.caveat':'Forme récente uniquement.',
    'bestxi.heuristic_warning':'Notes personnalisées indisponibles pour la Botola/MENA — scores heuristiques affichés.',
    'bestxi.optimised':'Optimisé',
    'bestxi.manually_edited':'Modifié manuellement',
    'bestxi.eligible':'ÉLIGIBLES',
    'bestxi.reset_optimal':'Rétablir l\'optimal',
    'bestxi.autofill':'Remplissage auto',
    'bestxi.export_png':'Exporter PNG',
    'bestxi.share_xi':'Partager',
    'bestxi.optimiser_details':'Détails de l\'optimiseur',
    'bestxi.detail_formation':'Schéma',
    'bestxi.detail_window':'Période',
    'bestxi.detail_method':'Méthode',
    'bestxi.detail_min_minutes':'Min. minutes',
    'bestxi.detail_buckets':'Niveaux',
    'bestxi.detail_candidates':'Candidats',
    'bestxi.detail_event_rated':'Données évén.',
    'bestxi.detail_mean_rating':'Note moyenne',
    'bestxi.detail_days':'jours',
    'bestxi.swap_note':'cliquer pour remplacer',
    'bestxi.status_doubtful':'Incertain',
    'bestxi.status_injured':'Blessé',
    'bestxi.status_suspended':'Suspendu',
    'bestxi.status_unknown':'Inconnu',
    'bestxi.caveat_label':'Avertissement',
    'bestxi.caveat_suffix':'Ce n\'est pas une recommandation de sélection — l\'adéquation tactique, la chimie et les blessures ne sont pas modélisées.',
    'bestxi.click_swap':'cliquez sur le slot pour effectuer un remplacement',
    'bestxi.player_status_alert':'({slot}) est {status}',
    'bestxi.detail_pool':'Taille du vivier',
    'bestxi.detail_data_quality':'Qualité des données',

    // ── players ───────────────────────────────────────────────────────────────
    'players.title':'JOUEURS',
    'players.next_gen':'★ La Prochaine Génération',
    'players.active_profiles':'{n} profils actifs',
    'players.lens_all':'Tous les joueurs',
    'players.lens_rising':'★ Jeunes talents',
    'players.rising_desc':'Joueurs de moins de {age} ans éligibles au Maroc — y compris les doubles nationaux transférables selon l\'Article 9 FIFA.',
    'players.article9_title':'Article 9 FIFA · Les données d\'éligibilité sont communautaires.',
    'players.article9_body':'Les joueurs qui détiennent la nationalité marocaine et n\'ont pas disputé de match officiel senior pour une autre association peuvent changer. Toujours vérifier auprès de la FRMF.',
    'players.filters':'Filtres',
    'players.sort_rating':'Note ↓',
    'players.sort_mv':'Valeur marchande ↓',
    'players.sort_age':'Âge ↑',
    'players.sort_minutes':'Minutes ↓',
    'players.sort_name':'Nom A→Z',
    'players.cancel_compare':'Annuler',
    'players.compare':'Comparer',
    'players.club_country':'Pays du club',
    'players.all':'Tous',
    'players.eligible':'Éligible',
    'players.switchable':'Transférable',
    'players.capped':'Sélectionné',
    'players.filter_position':'Poste',
    'players.filter_bucket':'Niveau de ligue',
    'players.filter_age_max':'Âge max',
    'players.filter_quality':'Qualité des données',
    'players.bucket_big5':'Big 5',
    'players.bucket_other_eu':'Autre EU',
    'players.bucket_botola':'Botola',
    'players.bucket_mena':'MENA',
    'players.reset_filters':'Réinitialiser',
    'players.showing':'{count} joueurs sur {total}',
    'players.grid':'Grille',
    'players.table':'Tableau',
    'players.selected_n':'{n} sélectionnés',
    'players.selected_min2':'choisissez au moins 2',
    'players.compare_n':'Comparer {n}',
    'players.col_player':'Joueur',
    'players.col_pos':'Poste',
    'players.col_club':'Club',
    'players.col_league':'Ligue',
    'players.col_rating':'Note',
    'players.col_mv':'VM',
    'players.col_min':'Min',
    'players.col_data':'Données',
    'players.col_elig':'Élig.',
    'players.age_controlled':'L\'âge est contrôlé par le filtre U-19/21/23 dans la vue Jeunes talents.',
    'players.loading':'Chargement des joueurs…',
    'players.no_match':'Aucun joueur trouvé',
    'players.no_match_desc':'Élargissez les filtres ou effacez la recherche.',
    'players.reset_all':'Tout réinitialiser',

    // ── player detail ─────────────────────────────────────────────────────────
    'player.breadcrumb_home':'Accueil',
    'player.breadcrumb_players':'Joueurs',
    'player.rating_30d':'Moy. 30j',
    'player.compare_btn':'Comparer →',
    'player.tab_performance':'Performance',
    'player.tab_history':'Historique des matchs',
    'player.form_averages':'Moyennes par fenêtre',
    'player.no_rating_data':'Aucune donnée de note — lancez une synchronisation.',
    'player.rating_history':'Historique · {n} derniers jours',
    'player.matches':'matchs',
    'player.filter_all':'Tous',
    'player.filter_national':'National',
    'player.filter_club':'Club',
    'player.heatmap_title':'Carte de forme · 365 derniers jours',
    'player.no_matches_window':'Aucun match dans cette fenêtre',
    'player.no_matches_window_desc':'Élargissez la fenêtre ou lancez une synchro.',
    'player.all_matches':'Tous les matchs',
    'player.no_match_data':'Aucune donnée de match',
    'player.no_match_data_desc':'Lancez une synchro pour récupérer les stats.',
    'player.col_date':'Date',
    'player.col_match':'Match',
    'player.col_competition':'Compétition',
    'player.col_min':'Min',
    'player.col_goals':'B',
    'player.col_assists':'P',
    'player.col_rating':'Note',
    'player.col_quality':'Qualité',
    'player.loading':'Chargement du joueur…',
    'player.not_found':'Joueur introuvable',
    'player.not_found_desc':'Vérifiez l\'URL ou parcourez l\'annuaire.',
    'player.back':'Retour aux joueurs',
    'player.stat_age':'Âge',
    'player.stat_height':'Taille',
    'player.stat_foot':'Pied',
    'player.stat_mv':'Valeur marchande',
    'player.stat_season_min':'Min. de saison',
    'player.rating':'Note','player.position':'Poste','player.club':'Club',
    'player.market_value':'Valeur marchande','player.age':'Âge','player.minutes':'Minutes',
    'player.archetype':'Archétype','player.eligibility':'Éligibilité','player.data_quality':'Qualité des données',

    // ── compare ───────────────────────────────────────────────────────────────
    'compare.eyebrow':'Jusqu\'à 4 joueurs · inter-ligues',
    'compare.title':'COMPARER',
    'compare.add_player':'Ajouter un joueur',
    'compare.radar_title':'Radar de profil',
    'compare.sidebyside_title':'Côte à côte',
    'compare.metric':'Indicateur',
    'compare.footnote':'Les comparaisons inter-ligues sont des scores Z positionnels par niveau. Les ligues avec notes heuristiques ne sont pas directement comparables aux ligues avec données événementielles — voir Méthodologie.',
    'compare.need_two':'Ajoutez au moins 2 joueurs pour les comparer côte à côte.',
    'compare.picker_subtitle':'Choisissez n\'importe qui dans la base de données',
    'compare.metric_rating':'Note',
    'compare.metric_attack':'Attaque',
    'compare.metric_defence':'Défense',
    'compare.metric_passing':'Passes',
    'compare.metric_dribble':'Dribbles',
    'compare.metric_minutes':'Minutes',
    'compare.metric_value':'Valeur',
    'compare.metric_xt':'xT/90',

    // ── fixtures ──────────────────────────────────────────────────────────────
    'fixtures.eyebrow':'Centre des matchs',
    'fixtures.title':'MATCHS',
    'fixtures.live_now':'EN DIRECT',
    'fixtures.bucket_all':'Tous',
    'fixtures.bucket_big5':'Big 5',
    'fixtures.bucket_other_eu':'Autre EU',
    'fixtures.bucket_botola':'Botola',
    'fixtures.bucket_mena':'MENA',
    'fixtures.bucket_international':'International',
    'fixtures.sort_date':'Par date',
    'fixtures.sort_competition':'Par compétition',
    'fixtures.sort_players':'Par effectif Lions',
    'fixtures.nt_only':'NT uniquement',
    'fixtures.list':'Liste',
    'fixtures.calendar':'Calendrier',
    'fixtures.type_international':'International',
    'fixtures.type_continental':'Continental',
    'fixtures.type_cup':'Coupe',
    'fixtures.type_league':'Championnat',
    'fixtures.today':'AUJOURD\'HUI',
    'fixtures.matches':'MATCHS',
    'fixtures.prev':'‹ Préc',
    'fixtures.next':'Suiv ›',
    'fixtures.close':'Fermer ×',
    'fixtures.no_fixtures':'Aucun match',
    'fixtures.no_fixtures_desc':'Aucun match ne correspond aux filtres actuels.',
    'fixtures.by_lions':'Par nombre de Lions impliqués',
    'fixtures.atlas_on_pitch':'Lions de l\'Atlas sur le terrain',

    // ── stats ─────────────────────────────────────────────────────────────────
    'stats.eyebrow':'Équipe nationale · {year} · {n} internationaux',
    'stats.title':'MAROC — LIONS DE L\'ATLAS',
    'stats.form_last10':'Forme · 10 derniers',
    'stats.goals_scored':'Buts marqués',
    'stats.goals_conceded':'Buts encaissés',
    'stats.clean_sheets':'Clean sheets',
    'stats.win_rate':'Taux de victoire',
    'stats.vs_prev':'vs {year}',
    'stats.goals_chart_title':'Buts par match',
    'stats.goals_chart_sub':'20 derniers internationaux',
    'stats.xg_chart_title':'xG vs buts marqués',
    'stats.xg_chart_sub':'Finition vs attendu · 20 derniers',
    'stats.top_contrib':'Meilleurs contributeurs',
    'stats.top_contrib_sub':'Notes Maroc uniquement · 365 derniers jours',
    'stats.col_rank':'#',
    'stats.col_player':'Joueur',
    'stats.col_caps':'Sél.',
    'stats.col_goals':'B',
    'stats.col_assists':'P',
    'stats.col_avg':'Moy.',
    'stats.recent_results':'Résultats récents',
    'stats.goals_label':'Buts',
    'stats.xg_label':'xG',

    // ── methodology ───────────────────────────────────────────────────────────
    'methodology.eyebrow':'Transparence',
    'methodology.title':'MÉTHODOLOGIE',
    'methodology.intro':'Comment Atlas Lions Analytics évalue chaque footballeur professionnel marocain et ce que les chiffres signifient réellement.',
    'methodology.rating_scale_title':'Échelle de notation',
    'methodology.rating_scale_body':'Nous utilisons l\'échelle Sofascore 3–10 comme référence. Sofascore couvre plus de 200 ligues et offre la couverture inter-compétitions la plus large disponible pour le football professionnel.',
    'methodology.tier_exceptional':'Exceptionnel',
    'methodology.tier_good':'Bon',
    'methodology.tier_belowpar':'En dessous',
    'methodology.quality_title':'Niveaux de qualité des données',
    'methodology.quality_body':'Toutes les notes ne se valent pas. Chaque note est accompagnée d\'un badge indiquant la fiabilité des données sous-jacentes.',
    'methodology.event_title':'Données événementielles — modèle xT/VAEP',
    'methodology.event_body':'Disponible pour le Big 5 (Premier League, La Liga, Bundesliga, Serie A, Ligue 1) et la Saudi Pro League. Utilise les données open de StatsBomb pour calculer la menace attendue (xT) et la valeur des actions (VAEP). Normalisé sur l\'échelle 4–9.',
    'methodology.commercial_title':'Note commerciale — Sofascore',
    'methodology.commercial_body':'La note brute Sofascore, utilisée pour les ligues hors Big 5 + SPL. Couvre la Botola Pro, la Ligue 1 Professionnelle et la plupart des autres ligues suivies.',
    'methodology.heuristic_title':'Heuristique — estimation dérivée',
    'methodology.heuristic_body':'Pour les ligues avec une couverture Sofascore incomplète, une estimation de forme est dérivée des données partielles : minutes jouées, buts, passes décisives et clean sheets. À traiter comme des guides approximatifs uniquement.',
    'methodology.bestxi_title':'L\'optimiseur du Onze idéal',
    'methodology.bestxi_body':'Le Onze idéal utilise l\'algorithme hongrois (Kuhn-Munkres) — un optimiseur d\'affectation O(n³) — pour trouver l\'affectation optimale des joueurs aux postes de la formation.',
    'methodology.bestxi_callout':'Algorithme : Nous construisons une matrice de coûts où coût(joueur, poste) = 10 − note_forme si joueur.pos ∈ poste.positionsÉligibles, sinon ∞. L\'algorithme minimise le coût total, ce qui équivaut à maximiser la note totale.',
    'methodology.bestxi_body2':'Si moins de 11 joueurs atteignent le seuil de minutes minimum, le système assouplit le seuil à 0 et affiche un avertissement "Assoupli".',
    'methodology.league_weighting_title':'Pondération des ligues',
    'methodology.league_weighting_body':'Les ligues sont regroupées en niveaux. Le niveau affecte l\'éligibilité des joueurs pour les calculs du Onze idéal et la pondération des notes dans les comparaisons inter-niveaux.',
    'methodology.col_bucket':'Niveau',
    'methodology.col_leagues':'Ligues',
    'methodology.col_quality':'Qualité des données',
    'methodology.col_weight':'Pondération',
    'methodology.eligibility_title':'Classification de l\'éligibilité',
    'methodology.eligibility_body':'Chaque joueur est classé dans l\'une des quatre catégories d\'éligibilité :',
    'methodology.elig_capped_label':'Sélectionné',
    'methodology.elig_capped_desc':'A disputé un match officiel senior international avec le Maroc (ou est déjà lié au Maroc).',
    'methodology.elig_eligible_label':'Éligible',
    'methodology.elig_eligible_desc':'Détient la nationalité marocaine et n\'a pas été sélectionné par aucune équipe nationale senior. Peut jouer pour le Maroc immédiatement.',
    'methodology.elig_switchable_label':'Transférable',
    'methodology.elig_switchable_desc':'Actuellement inscrit avec une autre équipe nationale mais n\'a pas encore disputé de match officiel. Peut rejoindre le Maroc selon l\'Article 9 FIFA s\'il détient la citoyenneté marocaine.',
    'methodology.elig_prospect_label':'Prospect',
    'methodology.elig_prospect_desc':'A des origines marocaines mais la double nationalité n\'est pas confirmée ou est complexe. Source communautaire ; vérifier indépendamment.',
    'methodology.caveats_title':'Mises en garde et limitations',
    'methodology.caveats_callout':'Ce n\'est pas une recommandation de sélection. Les notes reflètent uniquement la forme statistique récente et ne tiennent pas compte de l\'adéquation tactique, de la chimie d\'équipe, des facteurs psychologiques ou des préférences du coach.',
    'methodology.caveats_body':'Limitations supplémentaires à prendre en compte :',
    'methodology.caveat1':'Les joueurs avec moins de 90 minutes dans la fenêtre sélectionnée peuvent avoir des notes instables en raison d\'un petit échantillon.',
    'methodology.caveat2':'Les notes Sofascore peuvent être affectées par le contexte du match — un joueur qui marque à la 88e minute dans un 1-0 peut recevoir une note disproportionnellement élevée.',
    'methodology.caveat3':'Les comparaisons inter-ligues doivent être traitées avec prudence. Un 7,5 en Botola n\'est pas équivalent à un 7,5 en Premier League.',
    'methodology.caveat4':'Les données d\'éligibilité sont communautaires et peuvent être obsolètes. Vérifiez toujours auprès du club du joueur ou de la FRMF.',
    'methodology.caveat5':'Cette plateforme n\'est pas affiliée à la FRMF, la Fédération Royale Marocaine de Football.',
    'methodology.sources_title':'Sources de données',
    'methodology.source_sofascore':'Notes de match pour 200+ ligues',
    'methodology.source_apifootball':'Scores en direct, matchs, compositions',
    'methodology.source_transfermarkt':'Valeurs marchandes, historique de carrière',
    'methodology.source_wikidata':'Nationalité et données biographiques',
    'methodology.source_statsbomb':'Données événementielles xT/VAEP (Big 5)',
    'methodology.source_fbref':'Statistiques avancées pour le Big 5',

    // ── notfound ──────────────────────────────────────────────────────────────
    'notfound.title':'PAGE INTROUVABLE',
    'notfound.desc':'La page que vous recherchez n\'existe pas. Elle a peut-être été déplacée, ou l\'URL est incorrecte.',
    'notfound.go_home':'Accueil',
    'notfound.browse':'Parcourir les joueurs',

    // ── footer ────────────────────────────────────────────────────────────────
    'footer.tagline':'Des insights basés sur les données pour les Lions de l\'Atlas — chaque joueur marocain, chaque ligue, chaque week-end.',
    'footer.disclaimer':'Les classements reflètent uniquement la forme récente — pas une recommandation de sélection. Non affilié à la FRMF.',
    'footer.navigate':'Navigation',
    'footer.sources':'Sources de données',

    // ── common ────────────────────────────────────────────────────────────────
    'common.loading':'Chargement…','common.search':'Rechercher…','common.filter':'Filtrer',
    'common.reset':'Réinitialiser','common.share':'Partager','common.view_all':'Tout voir',
  },

  // ════════════════════════════════════════════════════════════════════════════
  ar: {
    // ── nav ──────────────────────────────────────────────────────────────────
    'nav.home':'الرئيسية','nav.bestxi':'أفضل تشكيلة','nav.players':'اللاعبون','nav.fixtures':'المباريات',
    'nav.stats':'الإحصاءات','nav.compare':'مقارنة','nav.methodology':'المنهجية',

    // ── home ─────────────────────────────────────────────────────────────────
    'home.hero_eyebrow':'آخر تحديث منذ ساعتين · الجولة 38',
    'home.hero_title1':'أفضل تشكيلة.',
    'home.hero_title2':'الآن.',
    'home.hero_body':'تقييمات قائمة على البيانات لكل لاعب كرة قدم محترف مغربي في العالم — من الدوري الإسباني إلى البطولة المغربية والدوري السعودي. تحديث يومي.',
    'home.btn_build':'بناء أفضل تشكيلة',
    'home.btn_browse':'استعراض اللاعبين',
    'home.counter_players':'لاعب يُتابَع',
    'home.counter_leagues':'بطولة تحت المراقبة',
    'home.counter_matches':'مباراة مفهرسة',
    'home.form_guide':'دليل الشكل',
    'home.current_xi_title':'التشكيلة الحالية',
    'home.current_xi_subtitle':'4-3-3 · آخر 30 يوماً · جميع المسابقات',
    'home.customise':'تخصيص',
    'home.starting_xi_label':'التشكيلة الأساسية · الأعلى تقييماً',
    'home.more_click':'+ 4 آخرون · انقر على "تخصيص" لتغيير الخطة والفترة',
    'home.rising_eyebrow':'↑ دليل الشكل',
    'home.rising_title':'في صعود — آخر 14 يوماً',
    'home.rising_subtitle':'اللاعبون الذين حققوا أكبر قفزة في التقييم',
    'home.nt_eyebrow':'أسود الأطلس',
    'home.nt_title':'المباريات الدولية القادمة',
    'home.no_fixtures':'لا توجد مباريات قادمة',
    'home.method_eyebrow':'المنهجية',
    'home.method_title':'كيف نقيّم',
    'home.method_body':'كل تقييم مصحوب بشارة جودة البيانات. نستخدم سوفاسكور للتغطية الشاملة ونموذجاً مخصصاً xT/VAEP للدوريات الكبرى والسعودي.',
    'home.method_btn':'اقرأ المنهجية',
    'home.atlas_on_pitch':'أسود الأطلس في الميدان',

    // ── bestxi ───────────────────────────────────────────────────────────────
    'bestxi.title':'بناء أفضل تشكيلة',
    'bestxi.flagship':'الرائد',
    'bestxi.page_title':'بناء أفضل تشكيلة',
    'bestxi.description':'اختر خطة ، فترة زمنية، والبطولات المعنية. يختار المحسِّن أعلى اللاعبين تقييماً لكل مركز. انقر على أي موقع للتبديل.',
    'bestxi.formation':'الخطة',
    'bestxi.window':'الفترة',
    'bestxi.window_2mw':'جولتان',
    'bestxi.window_1mo':'شهر',
    'bestxi.window_2mo':'شهران',
    'bestxi.window_3mo':'3 أشهر',
    'bestxi.league_filter':'تصفية البطولات',
    'bestxi.bucket_all':'الكل',
    'bestxi.bucket_clear':'مسح',
    'bestxi.rating_method':'طريقة التقييم',
    'bestxi.method_commercial_title':'تجاري',
    'bestxi.method_commercial_sub':'سوفاسكور — 200+ بطولة',
    'bestxi.method_custom_title':'xT/VAEP',
    'bestxi.method_custom_sub':'بيانات أحداث — الكبار + السعودي',
    'bestxi.min_minutes':'الحد الأدنى للدقائق',
    'bestxi.min_minutes_note':'اللاعبون بأقل من الحد المطلوب من الدقائق يُستبعدون.',
    'bestxi.generate':'إنشاء التشكيلة',
    'bestxi.optimising':'جارٍ التحسين…',
    'bestxi.commercial':'تجاري',
    'bestxi.custom':'xT/VAEP',
    'bestxi.caveat':'تعكس الترتيبات الأداء الأخير فقط.',
    'bestxi.heuristic_warning':'التقييم المخصص غير متاح لدوري البطولة/منطقة الشرق الأوسط — يتم عرض النتائج التقريبية.',
    'bestxi.optimised':'محسَّن',
    'bestxi.manually_edited':'معدَّل يدوياً',
    'bestxi.eligible':'مؤهل',
    'bestxi.reset_optimal':'استعادة الأمثل',
    'bestxi.autofill':'ملء تلقائي',
    'bestxi.export_png':'تصدير PNG',
    'bestxi.share_xi':'مشاركة',
    'bestxi.optimiser_details':'تفاصيل المحسِّن',
    'bestxi.detail_formation':'الخطة',
    'bestxi.detail_window':'الفترة',
    'bestxi.detail_method':'الطريقة',
    'bestxi.detail_min_minutes':'الحد الأدنى للدقائق',
    'bestxi.detail_buckets':'المستويات',
    'bestxi.detail_candidates':'المرشحون',
    'bestxi.detail_event_rated':'بيانات أحداث',
    'bestxi.detail_mean_rating':'متوسط التقييم',
    'bestxi.detail_days':'يوم',
    'bestxi.swap_note':'انقر للتبديل',
    'bestxi.status_doubtful':'مشكوك في لعبه',
    'bestxi.status_injured':'مصاب',
    'bestxi.status_suspended':'موقوف',
    'bestxi.status_unknown':'غير معروف',
    'bestxi.caveat_label':'تحذير',
    'bestxi.caveat_suffix':'هذا ليس توصية باختيار لاعبين — الملاءمة التكتيكية والانسجام والإصابات غير مدرجة في النموذج.',
    'bestxi.click_swap':'انقر على الموقع للتبديل',
    'bestxi.player_status_alert':'({slot}) {status}',
    'bestxi.detail_pool':'حجم المجموعة',
    'bestxi.detail_data_quality':'جودة البيانات',

    // ── players ───────────────────────────────────────────────────────────────
    'players.title':'اللاعبون',
    'players.next_gen':'★ الجيل القادم',
    'players.active_profiles':'{n} ملف نشط',
    'players.lens_all':'جميع اللاعبين',
    'players.lens_rising':'★ النجوم الصاعدون',
    'players.rising_desc':'لاعبون دون سن {age} مؤهلون للمغرب — بمن فيهم أصحاب الجنسيتين القابلين للتحويل وفق المادة 9 من قواعد الفيفا.',
    'players.article9_title':'المادة 9 من قواعد الفيفا · بيانات الأهلية مصدرها المجتمع.',
    'players.article9_body':'اللاعبون الذين يحملون الجنسية المغربية ولم يشاركوا في مباريات رسمية للفئة الأولى مع منتخب آخر يمكنهم التحويل. تحقق دائماً مع الجامعة الملكية المغربية لكرة القدم.',
    'players.filters':'التصفية',
    'players.sort_rating':'التقييم ↓',
    'players.sort_mv':'القيمة السوقية ↓',
    'players.sort_age':'العمر ↑',
    'players.sort_minutes':'الدقائق ↓',
    'players.sort_name':'الاسم أ→ي',
    'players.cancel_compare':'إلغاء المقارنة',
    'players.compare':'مقارنة',
    'players.club_country':'دولة النادي',
    'players.all':'الكل',
    'players.eligible':'مؤهل',
    'players.switchable':'قابل للتحويل',
    'players.capped':'مُنتخب',
    'players.filter_position':'المركز',
    'players.filter_bucket':'مستوى البطولة',
    'players.filter_age_max':'الحد الأقصى للعمر',
    'players.filter_quality':'جودة البيانات',
    'players.bucket_big5':'الكبار الخمسة',
    'players.bucket_other_eu':'أوروبا أخرى',
    'players.bucket_botola':'البطولة',
    'players.bucket_mena':'الشرق الأوسط',
    'players.reset_filters':'إعادة ضبط الفلاتر',
    'players.showing':'عرض {count} من {total} لاعب',
    'players.grid':'شبكة',
    'players.table':'جدول',
    'players.selected_n':'{n} محدد',
    'players.selected_min2':'اختر لاعبَين على الأقل',
    'players.compare_n':'مقارنة {n}',
    'players.col_player':'اللاعب',
    'players.col_pos':'المركز',
    'players.col_club':'النادي',
    'players.col_league':'البطولة',
    'players.col_rating':'التقييم',
    'players.col_mv':'القيمة',
    'players.col_min':'دق',
    'players.col_data':'البيانات',
    'players.col_elig':'الأهلية',
    'players.age_controlled':'يتم التحكم في العمر عبر مرشح أقل من 19/21/23 في عرض النجوم الصاعدين.',
    'players.loading':'جار تحميل اللاعبين…',
    'players.no_match':'لا يوجد لاعبون مطابقون',
    'players.no_match_desc':'حاول توسيع التصفية أو مسح البحث.',
    'players.reset_all':'إعادة ضبط الكل',

    // ── player detail ─────────────────────────────────────────────────────────
    'player.breadcrumb_home':'الرئيسية',
    'player.breadcrumb_players':'اللاعبون',
    'player.rating_30d':'متوسط 30 يوم',
    'player.compare_btn':'مقارنة ←',
    'player.tab_performance':'الأداء',
    'player.tab_history':'تاريخ المباريات',
    'player.form_averages':'متوسطات الأداء حسب الفترة',
    'player.no_rating_data':'لا توجد بيانات تقييم — قم بتشغيل المزامنة.',
    'player.rating_history':'سجل التقييمات · آخر {n} يوم',
    'player.matches':'مباريات',
    'player.filter_all':'الكل',
    'player.filter_national':'دولي',
    'player.filter_club':'نادي',
    'player.heatmap_title':'خريطة الشكل · آخر 365 يوماً',
    'player.no_matches_window':'لا توجد مباريات في هذه الفترة',
    'player.no_matches_window_desc':'جرب فترة أوسع أو قم بتشغيل المزامنة.',
    'player.all_matches':'جميع المباريات',
    'player.no_match_data':'لا توجد بيانات مباريات',
    'player.no_match_data_desc':'قم بتشغيل المزامنة لجلب إحصاءات المباريات.',
    'player.col_date':'التاريخ',
    'player.col_match':'المباراة',
    'player.col_competition':'المسابقة',
    'player.col_min':'دق',
    'player.col_goals':'أه',
    'player.col_assists':'تم',
    'player.col_rating':'التقييم',
    'player.col_quality':'الجودة',
    'player.loading':'جار تحميل اللاعب…',
    'player.not_found':'اللاعب غير موجود',
    'player.not_found_desc':'تحقق من الرابط أو تصفح القائمة.',
    'player.back':'العودة للاعبين',
    'player.stat_age':'العمر',
    'player.stat_height':'الطول',
    'player.stat_foot':'القدم',
    'player.stat_mv':'القيمة السوقية',
    'player.stat_season_min':'دقائق الموسم',
    'player.rating':'التقييم','player.position':'المركز','player.club':'النادي',
    'player.market_value':'القيمة السوقية','player.age':'العمر','player.minutes':'الدقائق',
    'player.archetype':'النمط','player.eligibility':'الأهلية','player.data_quality':'جودة البيانات',

    // ── compare ───────────────────────────────────────────────────────────────
    'compare.eyebrow':'حتى 4 لاعبين · عبر البطولات',
    'compare.title':'مقارنة',
    'compare.add_player':'إضافة لاعب',
    'compare.radar_title':'مخطط الملف',
    'compare.sidebyside_title':'مقارنة جانبية',
    'compare.metric':'المؤشر',
    'compare.footnote':'المقارنات عبر البطولات هي نقاط z موضعية داخل المجموعة. البطولات ذات التقييمات التقريبية لا يمكن مقارنتها مباشرة مع بطولات البيانات الحدثية — راجع المنهجية.',
    'compare.need_two':'أضف لاعبَين على الأقل للمقارنة.',
    'compare.picker_subtitle':'اختر أي لاعب من قاعدة البيانات',
    'compare.metric_rating':'التقييم',
    'compare.metric_attack':'الهجوم',
    'compare.metric_defence':'الدفاع',
    'compare.metric_passing':'التمرير',
    'compare.metric_dribble':'المراوغة',
    'compare.metric_minutes':'الدقائق',
    'compare.metric_value':'القيمة',
    'compare.metric_xt':'xT/90',

    // ── fixtures ──────────────────────────────────────────────────────────────
    'fixtures.eyebrow':'مركز المباريات',
    'fixtures.title':'المباريات',
    'fixtures.live_now':'مباشر الآن',
    'fixtures.bucket_all':'الكل',
    'fixtures.bucket_big5':'الكبار الخمسة',
    'fixtures.bucket_other_eu':'أوروبا أخرى',
    'fixtures.bucket_botola':'البطولة',
    'fixtures.bucket_mena':'الشرق الأوسط',
    'fixtures.bucket_international':'دولي',
    'fixtures.sort_date':'حسب التاريخ',
    'fixtures.sort_competition':'حسب المسابقة',
    'fixtures.sort_players':'حسب عدد الأسود',
    'fixtures.nt_only':'المنتخب فقط',
    'fixtures.list':'قائمة',
    'fixtures.calendar':'تقويم',
    'fixtures.type_international':'دولي',
    'fixtures.type_continental':'قاري',
    'fixtures.type_cup':'كأس',
    'fixtures.type_league':'دوري',
    'fixtures.today':'اليوم',
    'fixtures.matches':'مباريات',
    'fixtures.prev':'‹ السابق',
    'fixtures.next':'التالي ›',
    'fixtures.close':'إغلاق ×',
    'fixtures.no_fixtures':'لا توجد مباريات',
    'fixtures.no_fixtures_desc':'لا توجد مباريات تطابق الفلاتر الحالية.',
    'fixtures.by_lions':'حسب عدد الأسود المشاركين',
    'fixtures.atlas_on_pitch':'أسود الأطلس في الميدان',

    // ── stats ─────────────────────────────────────────────────────────────────
    'stats.eyebrow':'المنتخب الوطني · {year} · {n} مباراة دولية',
    'stats.title':'المغرب — أسود الأطلس',
    'stats.form_last10':'الشكل · آخر 10',
    'stats.goals_scored':'أهداف مسجَّلة',
    'stats.goals_conceded':'أهداف مُستقبَلة',
    'stats.clean_sheets':'شباك نظيفة',
    'stats.win_rate':'نسبة الفوز',
    'stats.vs_prev':'مقارنة بـ {year}',
    'stats.goals_chart_title':'الأهداف لكل مباراة',
    'stats.goals_chart_sub':'آخر 20 مباراة دولية',
    'stats.xg_chart_title':'xG مقابل الأهداف',
    'stats.xg_chart_sub':'الإنهاء مقابل المتوقع · آخر 20',
    'stats.top_contrib':'أفضل المساهمين',
    'stats.top_contrib_sub':'تقييمات المغرب فقط · آخر 365 يوماً',
    'stats.col_rank':'#',
    'stats.col_player':'اللاعب',
    'stats.col_caps':'مباريات',
    'stats.col_goals':'أه',
    'stats.col_assists':'تم',
    'stats.col_avg':'متوسط',
    'stats.recent_results':'النتائج الأخيرة',
    'stats.goals_label':'أهداف',
    'stats.xg_label':'xG',

    // ── methodology ───────────────────────────────────────────────────────────
    'methodology.eyebrow':'الشفافية',
    'methodology.title':'المنهجية',
    'methodology.intro':'كيف تقيّم أسود الأطلس أناليتيكس كل لاعب كرة قدم محترف مغربي وماذا تعني الأرقام فعلاً.',
    'methodology.rating_scale_title':'سلم التقييم',
    'methodology.rating_scale_body':'نستخدم سلم سوفاسكور من 3 إلى 10 كأساس. يغطي سوفاسكور أكثر من 200 دوري ويوفر أوسع تغطية عبر المسابقات المتاحة لكرة القدم الاحترافية.',
    'methodology.tier_exceptional':'استثنائي',
    'methodology.tier_good':'جيد',
    'methodology.tier_belowpar':'دون المستوى',
    'methodology.quality_title':'مستويات جودة البيانات',
    'methodology.quality_body':'ليست جميع التقييمات متساوية. كل تقييم مصحوب بشارة تشير إلى مدى موثوقية البيانات الأساسية.',
    'methodology.event_title':'بيانات الأحداث — نموذج xT/VAEP',
    'methodology.event_body':'متاح لبطولات الخمسة الكبار والدوري السعودي. يستخدم بيانات StatsBomb المفتوحة لحساب التهديد المتوقع (xT) وقيمة الأفعال (VAEP). منظّم على سلم 4–9.',
    'methodology.commercial_title':'التقييم التجاري — سوفاسكور',
    'methodology.commercial_body':'تقييم سوفاسكور الخام، يُستخدم للبطولات خارج الخمسة الكبار والدوري السعودي. يغطي البطولة الاحترافية المغربية ودوري الدرجة الأولى وغيرها.',
    'methodology.heuristic_title':'التقديري — تقدير مشتق',
    'methodology.heuristic_body':'للبطولات ذات التغطية الجزئية، نشتق تقدير الشكل من البيانات الجزئية المتاحة: الدقائق والأهداف والتمريرات الحاسمة. تعامل معها كمؤشرات تقريبية فقط.',
    'methodology.bestxi_title':'محسِّن أفضل تشكيلة',
    'methodology.bestxi_body':'تستخدم أفضل تشكيلة خوارزمية هنغاريان (Kuhn-Munkres) — محسِّن تخصيص O(n³) — للعثور على التوزيع الأمثل للاعبين على مراكز التشكيلة.',
    'methodology.bestxi_callout':'الخوارزمية: نبني مصفوفة تكاليف حيث التكلفة(لاعب، مركز) = 10 − تقييم_الشكل إذا كان مركز اللاعب ضمن المراكز المؤهلة، وإلا ∞. الخوارزمية تقلل التكلفة الإجمالية وهو ما يعادل تعظيم مجموع التقييمات.',
    'methodology.bestxi_body2':'إذا كان عدد اللاعبين الذين يستوفون الحد الأدنى للدقائق أقل من 11، يُخفف النظام الحد إلى 0 ويعرض تحذير "مُخفَّف".',
    'methodology.league_weighting_title':'ترجيح البطولات',
    'methodology.league_weighting_body':'تُجمَّع البطولات في مستويات. يؤثر المستوى على أهلية اللاعبين لحسابات أفضل تشكيلة وترجيح التقييمات في المقارنات بين المستويات.',
    'methodology.col_bucket':'المستوى',
    'methodology.col_leagues':'البطولات',
    'methodology.col_quality':'جودة البيانات',
    'methodology.col_weight':'الترجيح',
    'methodology.eligibility_title':'تصنيف الأهلية',
    'methodology.eligibility_body':'يُصنَّف كل لاعب في إحدى الفئات الأربع:',
    'methodology.elig_capped_label':'مُنتخب',
    'methodology.elig_capped_desc':'شارك في مباراة رسمية دولية للكبار مع المغرب.',
    'methodology.elig_eligible_label':'مؤهل',
    'methodology.elig_eligible_desc':'يحمل الجنسية المغربية ولم يُستدعَ من قِبل أي منتخب أول. يمكنه اللعب للمغرب فوراً.',
    'methodology.elig_switchable_label':'قابل للتحويل',
    'methodology.elig_switchable_desc':'مسجل حالياً مع منتخب آخر لكنه لم يشارك بعد في مباراة رسمية. يمكنه الانضمام للمغرب وفق المادة 9 من قواعد الفيفا.',
    'methodology.elig_prospect_label':'موهبة محتملة',
    'methodology.elig_prospect_desc':'له جذور مغربية لكن الجنسية المزدوجة غير مؤكدة أو معقدة. مصدرها المجتمع؛ تحقق بشكل مستقل.',
    'methodology.caveats_title':'تحفظات وقيود',
    'methodology.caveats_callout':'هذا ليس توصية باختيار لاعبين. تعكس التقييمات الشكل الإحصائي الأخير فقط ولا تأخذ بعين الاعتبار الملاءمة التكتيكية أو العوامل النفسية أو تفضيلات المدرب.',
    'methodology.caveats_body':'قيود إضافية يجب معرفتها:',
    'methodology.caveat1':'اللاعبون بأقل من 90 دقيقة في الفترة المختارة قد تكون تقييماتهم غير مستقرة.',
    'methodology.caveat2':'يمكن أن تتأثر تقييمات سوفاسكور بسياق المباراة — لاعب يسجل في الدقيقة 88 قد يحصل على تقييم مبالغ فيه.',
    'methodology.caveat3':'يجب التعامل مع المقارنات بين البطولات بحذر. 7.5 في البطولة المغربية ليس مساوياً لـ 7.5 في الدوري الإنجليزي.',
    'methodology.caveat4':'بيانات الأهلية مصدرها المجتمع وقد تكون قديمة. تحقق دائماً مع نادي اللاعب أو الجامعة الملكية.',
    'methodology.caveat5':'هذه المنصة غير مرتبطة بالجامعة الملكية المغربية لكرة القدم.',
    'methodology.sources_title':'مصادر البيانات',
    'methodology.source_sofascore':'تقييمات المباريات من 200+ دوري',
    'methodology.source_apifootball':'نتائج مباشرة، مباريات، تشكيلات',
    'methodology.source_transfermarkt':'القيم السوقية، السجل المهني',
    'methodology.source_wikidata':'الجنسية والبيانات السيرة ذاتية',
    'methodology.source_statsbomb':'بيانات أحداث xT/VAEP (الكبار الخمسة)',
    'methodology.source_fbref':'إحصاءات متقدمة للكبار الخمسة',

    // ── notfound ──────────────────────────────────────────────────────────────
    'notfound.title':'الصفحة غير موجودة',
    'notfound.desc':'الصفحة التي تبحث عنها غير موجودة. ربما تم نقلها أو الرابط غير صحيح.',
    'notfound.go_home':'الصفحة الرئيسية',
    'notfound.browse':'استعراض اللاعبين',

    // ── footer ────────────────────────────────────────────────────────────────
    'footer.tagline':'رؤى قائمة على البيانات لأسود الأطلس — كل محترف مغربي، كل بطولة، كل أسبوع.',
    'footer.disclaimer':'تعكس الترتيبات الشكل الأخير فقط — ليست توصية باختيار. غير مرتبطة بالجامعة الملكية المغربية.',
    'footer.navigate':'التنقل',
    'footer.sources':'مصادر البيانات',

    // ── common ────────────────────────────────────────────────────────────────
    'common.loading':'جار التحميل…','common.search':'بحث…','common.filter':'تصفية',
    'common.reset':'إعادة','common.share':'مشاركة','common.view_all':'عرض الكل',
  },
};

const LanguageContext = createContext({ locale: 'en', t: k => k, isRTL: false, setLocale: () => {} });

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState(() => localStorage.getItem('atlas-locale') || 'en');
  useEffect(() => {
    localStorage.setItem('atlas-locale', locale);
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
  }, [locale]);
  const t = useCallback(k => (STRINGS[locale]?.[k]) || STRINGS.en[k] || k, [locale]);
  return (
    <LanguageContext.Provider value={{ locale, t, isRTL: locale === 'ar', setLocale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useT = () => useContext(LanguageContext);
export default LanguageContext;
