// Formation slot definitions
// Coordinates match the design's 680×480 pitch SVG viewBox

const formations = {
  '4-3-3': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'LB',  slot:'LB', label:'LB', x:120, y:340, eligiblePositions:['LB','LWB','WB'] },
    { id:'CB1', slot:'CB', label:'CB', x:260, y:355, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:420, y:355, eligiblePositions:['CB'] },
    { id:'RB',  slot:'RB', label:'RB', x:560, y:340, eligiblePositions:['RB','RWB','WB'] },
    { id:'CM1', slot:'CM', label:'CM', x:200, y:240, eligiblePositions:['CM','CDM','CAM','DM','AM'] },
    { id:'CM2', slot:'CM', label:'CM', x:340, y:255, eligiblePositions:['CM','CDM','DM'] },
    { id:'CM3', slot:'CM', label:'CM', x:480, y:240, eligiblePositions:['CM','CDM','CAM','DM','AM'] },
    { id:'LW',  slot:'LW', label:'LW', x:140, y:120, eligiblePositions:['LW','LM','ST'] },
    { id:'ST',  slot:'ST', label:'ST', x:340, y:90,  eligiblePositions:['ST','SS','LW','RW','AM'] },
    { id:'RW',  slot:'RW', label:'RW', x:540, y:120, eligiblePositions:['RW','RM','ST'] },
  ],
  '4-4-2': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'LB',  slot:'LB', label:'LB', x:120, y:340, eligiblePositions:['LB','LWB','WB'] },
    { id:'CB1', slot:'CB', label:'CB', x:260, y:355, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:420, y:355, eligiblePositions:['CB'] },
    { id:'RB',  slot:'RB', label:'RB', x:560, y:340, eligiblePositions:['RB','RWB','WB'] },
    { id:'LM',  slot:'LM', label:'LM', x:130, y:230, eligiblePositions:['LM','LW','CM'] },
    { id:'CM1', slot:'CM', label:'CM', x:270, y:250, eligiblePositions:['CM','CDM','DM','AM'] },
    { id:'CM2', slot:'CM', label:'CM', x:410, y:250, eligiblePositions:['CM','CDM','DM','AM'] },
    { id:'RM',  slot:'RM', label:'RM', x:550, y:230, eligiblePositions:['RM','RW','CM'] },
    { id:'ST1', slot:'ST', label:'ST', x:260, y:110, eligiblePositions:['ST','SS','LW','AM'] },
    { id:'ST2', slot:'ST', label:'ST', x:420, y:110, eligiblePositions:['ST','SS','RW','AM'] },
  ],
  '4-2-3-1': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'LB',  slot:'LB', label:'LB', x:120, y:340, eligiblePositions:['LB','LWB','WB'] },
    { id:'CB1', slot:'CB', label:'CB', x:260, y:355, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:420, y:355, eligiblePositions:['CB'] },
    { id:'RB',  slot:'RB', label:'RB', x:560, y:340, eligiblePositions:['RB','RWB','WB'] },
    { id:'DM1', slot:'DM', label:'DM', x:260, y:260, eligiblePositions:['CDM','CM','DM'] },
    { id:'DM2', slot:'DM', label:'DM', x:420, y:260, eligiblePositions:['CDM','CM','DM'] },
    { id:'LW',  slot:'LW', label:'LW', x:140, y:160, eligiblePositions:['LW','LM','AM'] },
    { id:'AM',  slot:'AM', label:'AM', x:340, y:180, eligiblePositions:['CAM','AM','CM'] },
    { id:'RW',  slot:'RW', label:'RW', x:540, y:160, eligiblePositions:['RW','RM','AM'] },
    { id:'ST',  slot:'ST', label:'ST', x:340, y:80,  eligiblePositions:['ST','SS','LW','RW','AM'] },
  ],
  '3-5-2': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'CB1', slot:'CB', label:'CB', x:180, y:355, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:340, y:360, eligiblePositions:['CB'] },
    { id:'CB3', slot:'CB', label:'CB', x:500, y:355, eligiblePositions:['CB'] },
    { id:'WBL', slot:'WB', label:'WB', x:90,  y:250, eligiblePositions:['LWB','LB','WB','LM'] },
    { id:'CM1', slot:'CM', label:'CM', x:230, y:260, eligiblePositions:['CM','CDM','DM'] },
    { id:'CM2', slot:'CM', label:'CM', x:340, y:280, eligiblePositions:['CM','CDM','DM','AM'] },
    { id:'CM3', slot:'CM', label:'CM', x:450, y:260, eligiblePositions:['CM','CDM','DM'] },
    { id:'WBR', slot:'WB', label:'WB', x:590, y:250, eligiblePositions:['RWB','RB','WB','RM'] },
    { id:'ST1', slot:'ST', label:'ST', x:260, y:110, eligiblePositions:['ST','SS','LW','AM'] },
    { id:'ST2', slot:'ST', label:'ST', x:420, y:110, eligiblePositions:['ST','SS','RW','AM'] },
  ],
  '3-4-3': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'CB1', slot:'CB', label:'CB', x:180, y:355, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:340, y:360, eligiblePositions:['CB'] },
    { id:'CB3', slot:'CB', label:'CB', x:500, y:355, eligiblePositions:['CB'] },
    { id:'WBL', slot:'WB', label:'WB', x:90,  y:255, eligiblePositions:['LWB','LB','WB','LM'] },
    { id:'CM1', slot:'CM', label:'CM', x:260, y:260, eligiblePositions:['CM','CDM','DM'] },
    { id:'CM2', slot:'CM', label:'CM', x:420, y:260, eligiblePositions:['CM','CDM','DM'] },
    { id:'WBR', slot:'WB', label:'WB', x:590, y:255, eligiblePositions:['RWB','RB','WB','RM'] },
    { id:'LW',  slot:'LW', label:'LW', x:160, y:120, eligiblePositions:['LW','LM','ST'] },
    { id:'ST',  slot:'ST', label:'ST', x:340, y:90,  eligiblePositions:['ST','SS','LW','RW','AM'] },
    { id:'RW',  slot:'RW', label:'RW', x:520, y:120, eligiblePositions:['RW','RM','ST'] },
  ],
  '5-4-1': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'WBL', slot:'WB', label:'WB', x:90,  y:340, eligiblePositions:['LWB','LB','WB','LM'] },
    { id:'CB1', slot:'CB', label:'CB', x:220, y:360, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:340, y:365, eligiblePositions:['CB'] },
    { id:'CB3', slot:'CB', label:'CB', x:460, y:360, eligiblePositions:['CB'] },
    { id:'WBR', slot:'WB', label:'WB', x:590, y:340, eligiblePositions:['RWB','RB','WB','RM'] },
    { id:'LM',  slot:'LM', label:'LM', x:140, y:240, eligiblePositions:['LM','LW','CM'] },
    { id:'CM1', slot:'CM', label:'CM', x:270, y:260, eligiblePositions:['CM','CDM','DM','AM'] },
    { id:'CM2', slot:'CM', label:'CM', x:410, y:260, eligiblePositions:['CM','CDM','DM','AM'] },
    { id:'RM',  slot:'RM', label:'RM', x:540, y:240, eligiblePositions:['RM','RW','CM'] },
    { id:'ST',  slot:'ST', label:'ST', x:340, y:100, eligiblePositions:['ST','SS','LW','RW','AM'] },
  ],
  '5-3-2': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'WBL', slot:'WB', label:'WB', x:80,  y:330, eligiblePositions:['LWB','LB','WB','LM'] },
    { id:'CB1', slot:'CB', label:'CB', x:215, y:360, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:340, y:365, eligiblePositions:['CB'] },
    { id:'CB3', slot:'CB', label:'CB', x:465, y:360, eligiblePositions:['CB'] },
    { id:'WBR', slot:'WB', label:'WB', x:600, y:330, eligiblePositions:['RWB','RB','WB','RM'] },
    { id:'CM1', slot:'CM', label:'CM', x:230, y:240, eligiblePositions:['CM','CDM','DM'] },
    { id:'CM2', slot:'CM', label:'CM', x:340, y:258, eligiblePositions:['CM','CDM','DM','AM'] },
    { id:'CM3', slot:'CM', label:'CM', x:450, y:240, eligiblePositions:['CM','CDM','DM'] },
    { id:'ST1', slot:'ST', label:'ST', x:265, y:105, eligiblePositions:['ST','SS','LW','AM'] },
    { id:'ST2', slot:'ST', label:'ST', x:415, y:105, eligiblePositions:['ST','SS','RW','AM'] },
  ],
  '4-1-4-1': [
    { id:'GK',  slot:'GK', label:'GK', x:340, y:430, eligiblePositions:['GK'] },
    { id:'LB',  slot:'LB', label:'LB', x:120, y:345, eligiblePositions:['LB','LWB','WB'] },
    { id:'CB1', slot:'CB', label:'CB', x:260, y:358, eligiblePositions:['CB'] },
    { id:'CB2', slot:'CB', label:'CB', x:420, y:358, eligiblePositions:['CB'] },
    { id:'RB',  slot:'RB', label:'RB', x:560, y:345, eligiblePositions:['RB','RWB','WB'] },
    { id:'DM',  slot:'DM', label:'DM', x:340, y:285, eligiblePositions:['CDM','CM','DM'] },
    { id:'LM',  slot:'LM', label:'LM', x:120, y:185, eligiblePositions:['LM','LW','CM'] },
    { id:'CM1', slot:'CM', label:'CM', x:270, y:200, eligiblePositions:['CM','AM','CAM'] },
    { id:'CM2', slot:'CM', label:'CM', x:410, y:200, eligiblePositions:['CM','AM','CAM'] },
    { id:'RM',  slot:'RM', label:'RM', x:560, y:185, eligiblePositions:['RM','RW','CM'] },
    { id:'ST',  slot:'ST', label:'ST', x:340, y:90,  eligiblePositions:['ST','SS','LW','RW','AM'] },
  ],
};

module.exports = formations;
